version: '3'
services:
  app:
    build: .
    ports:
      - 3000:3000
    env_file:
      - docker.env
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis:latest
    ports:
      - 6379:6379

volumes:
  mongo-data: